AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AMAWSDEVUE101
Parameters:
  VpcCIDR:
    Description: CIDR block para la VPC
    Type: String
    Default: "10.0.0.0/16"
  
  AuroraDBInstanceType:
    Description: Tipo de instancia para Aurora PostgreSQL
    Type: String
    Default: "db.t3.medium"
    
  OpenSearchInstanceType:
    Description: Tipo de instancia para OpenSearch
    Type: String
    Default: "t3.small" 

  EFSVolumeSize:
    Description: Tamaño del volumen EFS para almacenamiento de embeddings
    Type: Number
    Default: 50 

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "VPC"

  DefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Default security group for EFS Mount Target
      VpcId: !Ref VPC

  SUPR1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Select [0, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "SUPR1"

  SUPR2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Select [1, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "SUPR2"

  SUPR3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: !Select [2, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "SUPR3"

  SUPR4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [3, !GetAZs ""]
      CidrBlock: !Select [3, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "SUPR4"

  EFSFileSystem:
    Type: "AWS::EFS::FileSystem"
    Properties:
      FileSystemTags:
        - Key: Name
          Value: "MyEFSFileSystem"

  EFSMountTarget:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref EFSFileSystem
      SubnetId: !Ref SUPR3
      SecurityGroups: 
        - !Ref DefaultSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for Aurora DB"
      SubnetIds:
        - !Ref SUPR1
        - !Ref SUPR2
        - !Ref SUPR3
        - !Ref SUPR4

  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      MasterUsername: masteruser
      MasterUserPassword: masterpassword
      DBSubnetGroupName: !Ref DBSubnetGroup


  OpenSearchServiceLinkedRole:
    Type: "AWS::IAM::ServiceLinkedRole"
    Properties:
      AWSServiceName: "es.amazonaws.com"
      Description: "Service linked role for Amazon OpenSearch Service"

  ElasticsearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: my-opensearch-nw
      NodeToNodeEncryptionOptions:
        Enabled: true
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
      VPCOptions:
        SubnetIds:
          - !Ref SUPR3
      AccessPolicies: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/my-opensearch-nw/*"

  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: MyEKSCluster
      RoleArn: !GetAtt EKSRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref SUPR1
          - !Ref SUPR3
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
  
  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  EKSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EKSPermissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - eks:DescribeCluster
              - eks:ListClusters
              - eks:ListFargateProfiles
              - eks:ListNodegroups
            Resource: "*"
      Roles:
        - !Ref EKSRole

  RDSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: RDSPermissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - rds:CreateDBCluster
              - rds:CreateDBInstance
              - rds:DescribeDBClusters
              - rds:DescribeDBInstances
            Resource: "*"
      Roles:
        - !Ref EKSRole

  EFSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EFSPermissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - elasticfilesystem:CreateFileSystem
              - elasticfilesystem:CreateMountTarget
              - elasticfilesystem:DescribeFileSystems
              - elasticfilesystem:DescribeMountTargets
            Resource: "*"
      Roles:
        - !Ref EKSRole

  OpenSearchPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: OpenSearchPermissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - es:*
            Resource: "*"
      Roles:
        - !Ref EKSRole

Outputs:
  VpcId:
    Description: ID de la VPC recién creada
    Value: !Ref VPC
