AWSTemplateFormatVersion: "2010-09-09"
Description: 
  AMAWSDEVUE101 

Parameters:
  VpcCIDR:
    Description: "Bloque CIDR para la VPC"
    Type: String
    Default: "10.0.0.0/16"
  
  AuroraDBInstanceType:
    Description: "Tipo de instancia para Aurora PostgreSQL"
    Type: String
    Default: "db.t3.medium"
    
  OpenSearchInstanceType:
    Description: "Tipo de instancia para OpenSearch"
    Type: String
    Default: "t3.small" 

  EFSVolumeSize:
    Description: "Tamaño del volumen EFS para almacenamiento de embeddings"
    Type: Number
    Default: 50 

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "AERONEXGAWSDEVVPCEAST201"
        - Key: Description
          Value: "VPC NextGenCC"
        - Key: Project
          Value: "NextGenCC"
        - Key: Environment
          Value: "Dev"
        - Key: Area
          Value: "Call Center"


  SUPR1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Select [0, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "AERONEXGAWSDEVSUPREAST201"
        - Key: Description
          Value: "SUPR1 NextGenCC"
        - Key: Project
          Value: "NextGenCC"
        - Key: Environment
          Value: "Dev"
        - Key: Area
          Value: "Call Center"

  SUPR2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Select [1, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "AERONEXGAWSDEVSUPREAST201"
        - Key: Description
          Value: "SUPR2 NextGenCC"
        - Key: Project
          Value: "NextGenCC"
        - Key: Environment
          Value: "Dev"
        - Key: Area
          Value: "Call Center"

  SUPR3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: !Select [2, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "AERONEXGAWSDEVSUPREAST201"
        - Key: Description
          Value: "SUPR3 NextGenCC"
        - Key: Project
          Value: "NextGenCC"
        - Key: Environment
          Value: "Dev"
        - Key: Area
          Value: "Call Center"

  SUPR4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [3, !GetAZs ""]
      CidrBlock: !Select [3, !Cidr [!Ref VpcCIDR, 4, 4]]
      Tags:
        - Key: Name
          Value: "AERONEXGAWSDEVSUPREAST201"
        - Key: Description
          Value: "SUPR4 NextGenCC"
        - Key: Project
          Value: "NextGenCC"
        - Key: Environment
          Value: "Dev"
        - Key: Area
          Value: "Call Center"

Outputs:
  VpcId:
    Description: >
      - VPC: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/${VPC}"
    Value: !Ref VPC